/// 200+ Vietnamese couple questions organized by category.
/// Used by deterministic daily question algorithm.
const List<String> kQuestionPool = [
  // ── Ky niem & Qua khu (Memories) ──────────────────────────────
  'Ky niem dau tien cua chung ta ma ban nho nhat la gi?',
  'Lan dau gap nhau, an tuong dau tien cua ban ve nguoi kia la gi?',
  'Khoảnh khac nao khien ban biet minh da yeu nguoi kia?',
  'Chuyen di choi nao cua chung ta ban thich nhat?',
  'Mon qua nao tu nguoi kia khien ban cam dong nhat?',
  'Buoi hen ho nao cua chung ta vui nhat?',
  'Ban co nho chung ta noi "Anh/Em yeu em/anh" lan dau khi nao khong?',
  'Dieu gi o thoi gian dau yeu khien ban nho nhat?',
  'Lan cuoi cung chung ta cuoi thuc su suong bung la khi nao?',
  'Bai hat nao lam ban nho den chung ta?',
  'Neu co the song lai mot ngay voi nhau, ban chon ngay nao?',
  'Hinh anh nao cua chung ta ban thich nhat?',
  'Cau chuyen hai huoc nhat ma chung ta tung trai qua?',
  'Lan dau ban ghen la khi nao?',
  'Dieu bat ngo nhat nguoi kia tung lam cho ban?',

  // ── Mo uoc & Tuong lai (Dreams) ──────────���────────────────────
  'Neu duoc di bat ky dau tren the gioi, ban muon di dau cung nhau?',
  'Ban mo uoc cuoc song cua chung ta sau 5 nam se nhu the nao?',
  'Ngoi nha mo uoc cua chung ta trong nhu the nao?',
  'Ban muon co may con? Ten gi?',
  'Muc tieu chung ma ban muon chung ta dat duoc trong nam nay?',
  'Neu trung so, dieu dau tien ban muon lam cung nhau la gi?',
  'Dia diem tuyet tran nhat ban muon song cung nhau?',
  'Ban muon dam cuoi cua chung ta se nhu the nao?',
  'Dieu gi ban muon ca hai cung hoc?',
  'Mot thu ban muon chung ta thu lam cung nhau?',
  'Ban muon chung ta co thu cung gi?',
  'Ky nghi mo uoc cua ban la gi?',
  'Ban muon viet gi trong tam thu gui cho nhau 10 nam sau?',
  'Dieu ban muon day con cai ve tinh yeu la gi?',
  'Ban tuong tuong buoi sang ly tuong cua chung ta the nao?',

  // ── Cam xuc & Tinh cam (Feelings) ───���─────────────────────────
  'Dieu gi o nguoi kia khien ban cam thay binh yen nhat?',
  'Khi nao ban cam thay duoc yeu thuong nhat?',
  'Dieu nho nhat nguoi kia lam ma khien ban hanh phuc?',
  'Ban cam thay nhu the nao khi xa nhau lau?',
  'Dieu gi khien ban tu hao nhat ve nguoi kia?',
  'Khi buon, ban muon nguoi kia lam gi cho ban?',
  'Ban yeu dieu gi nhat o nu cuoi cua nguoi kia?',
  'Cam giac cua ban khi nhan duoc tin nhan tu nguoi kia?',
  'Dieu gi nguoi kia lam khien ban cam thay duoc tran trong?',
  'Ban thay hanh phuc nhat khi chung ta lam gi?',
  'Khi gian nhau, ban muon duoc lam hoa nhu the nao?',
  'Dieu gi ban muon nguoi kia biet nhung chua noi?',
  'Ban cam thay the nao ve tuong lai cua chung ta?',
  'Luc nao ban cam thay gan gui voi nguoi kia nhat?',
  'Dieu gi o ban than ban muon nguoi kia hieu hon?',

  // ── So thich & Gu (Preferences) ────────���──────────────────────
  'Mon an ma ban muon duoc nguoi kia nau cho?',
  'Phim tinh cam nao ban muon xem cung nhau?',
  'Hoat dong cuoi tuan ly tuong cua ban la gi?',
  'Ban thich duoc om hay nam tay hon?',
  'Qua sinh nhat ly tuong ban muon nhan tu nguoi kia?',
  'Ban thich hen ho o nha hay di ra ngoai hon?',
  'Loai nhac nao ban muon nghe cung nhau?',
  'Mua nao trong nam ban thich nhat de di choi cung nhau?',
  'Ban thich duoc goi bang ten gi?',
  'Buoi sang ly tuong: ngu nuong hay day som cung nhau?',
  'Ban thich nhan hoa hay socola hon?',
  'Dieu gi ban muon lam cung nhau moi tuan?',
  'Ban thich gui tin nhan dai hay ngan gon?',
  'Kieu au yem nao ban thich nhat?',
  'Ban thich duoc bat ngo hay bao truoc?',

  // ── Gia dinh & GiaTri (Family & Values) ───────────────────────
  'Truyen thong gia dinh nao ban muon giữ lai?',
  'Dieu quan trong nhat trong mot moi quan he la gi?',
  'Ban hoc duoc gi tu bo me ve tinh yeu?',
  'Cach ban muon giai quyet xung dot trong moi quan he?',
  'Dieu gi ban khong bao gio chap nhan trong tinh yeu?',
  'Ban nghi the nao ve viec quan ly tai chinh chung?',
  'Vai tro cua gia dinh hai ben trong cuoc song chung ta?',
  'Dieu gi ban muon day nguoi kia ve gia dinh ban?',
  'Ban nghi nhu the nao ve viec chia se viec nha?',
  'Truyen thong moi nao ban muon tao cho rieng chung ta?',

  // ── Gia nhu & Tro choi (Hypotheticals) ────────────────────────
  'Neu chi duoc giu mot ky niem ve chung ta, ban chon ky niem nao?',
  'Neu duoc doi mot thu ve ban than, ban doi gi?',
  'Neu nguoi kia la mot mon an, do se la mon gi?',
  'Neu co sieu nang luc, ban muon co nang luc gi de bao ve nguoi kia?',
  'Neu chung ta bi ket tren dao hoang, ban muon mang theo gi?',
  'Neu duoc song o bat ky thoi dai nao, ban chon thoi dai nao?',
  'Neu nguoi kia la mot bai hat, do se la bai nao?',
  'Neu co mot ngay khong can lo lang gi, ban muon lam gi?',
  'Neu co the doc duoc suy nghi cua nhau trong 1 phut, ban muon biet gi?',
  'Neu chung ta trao doi than xac 1 ngay, ban se lam gi?',
  'Neu duoc quay lai thoi diem bat ky, ban chon luc nao?',
  'Neu co may thoi gian, ban muon di ve qua khu hay tuong lai?',
  'Neu nguoi kia la mot mau sac, do se la mau gi?',
  'Neu duoc tang nguoi kia 1 ngoi sao, ban dat ten gi?',
  'Neu chi con 24h, ban muon lam gi cung nhau?',

  // ── Hieu biet & Kham pha (Understanding) ──────────────────────
  'Ban biet gi ve uoc mo thoi nho cua nguoi kia?',
  'Dieu gi khien nguoi kia stress nhat?',
  'Thoi quen nao cua nguoi kia ban thay de thuong?',
  'Dieu gi khien nguoi kia bat cuoi?',
  'So thich bi mat nao cua nguoi kia ban moi phat hien?',
  'Mon an nao nguoi kia khong bao gio tu choi?',
  'Nguoi kia lam gi khi khong ai nhin?',
  'Dieu gi khien nguoi kia khong the ngu duoc?',
  'Ban biet gi ve noi so cua nguoi kia?',
  'Dieu gi o ban lam nguoi kia ghen?',
  'Ban nghi nguoi kia se mo ta ban nhu the nao voi ban be?',
  'Thoi quen nao cua nhau ban thay kho chiu nhung van yeu?',
  'Dieu gi nguoi kia hay lam khi vui?',
  'Ban biet gi ve nguoi ma nguoi kia ngưỡng mo nhat?',
  'Nguoi kia co dieu gi ban chua bao gio hoi?',

  // ── Yeu thuong & Bieu hien (Love Language) ────────────────────
  'Ban cam thay duoc yeu nhat khi nguoi kia lam gi?',
  'Cach ban the hien tinh yeu la gi?',
  'Ban thich duoc khen ve dieu gi?',
  'Hanh dong nho nao cua nguoi kia khien ban tan chay?',
  'Ban muon nhan duoc nhieu loi khen hay nhieu hanh dong hon?',
  'Viec nha nao ban san sang lam de nguoi kia vui?',
  'Ban thich duoc nhan qua bat ngo hay duoc chon qua?',
  'Cau noi nao ban muon nghe moi ngay tu nguoi kia?',
  'Thoi gian chat luong cua chung ta la lam gi?',
  'Ban muon duoc om bao lau?',

  // ── Thach thuc & Truong thanh (Growth) ────────────────────────
  'Dieu gi ban da hoc duoc tu moi quan he nay?',
  'Thoi quen nao ban muon ca hai cung thay doi?',
  'Ban da truong thanh nhu the nao ke tu khi yeu nhau?',
  'Dieu gi ban nghi la thu thach lon nhat cua chung ta?',
  'Ban muon cai thien dieu gi o ban than vi nguoi kia?',
  'Loi khuyen tinh yeu nao ban muon chia se voi nguoi khac?',
  'Dieu gi ban muon xin loi nhung chua lam?',
  'Ban nghi chung ta da vuot qua kho khan nhu the nao?',
  'Dieu gi ban muon ca hai no luc hon?',
  'Ban nghi bi quyet de tinh yeu ben lau la gi?',

  // ── Vui ve & Hai huoc (Fun) ───────────────────────────────────
  'Neu viet sach ve chung ta, tua de se la gi?',
  'Emoji nao dai dien cho moi quan he cua chung ta?',
  'Neu co bai hat chu de cho chung ta, bai nao?',
  'Dieu ngo ngan nhat ban tung lam vi yeu?',
  'Biet danh hai huoc nhat ban dat cho nguoi kia?',
  'Cau noi kinh dien nhat cua nguoi kia la gi?',
  'Neu quay clip TikTok cung nhau, noi dung gi?',
  'Dieu gi ban lam sai nhung nguoi kia van tha thu?',
  'Kieu chup anh yeu thich nhat cua chung ta?',
  'Neu mo quan an cung nhau, ban dat ten gi?',
  'Dieu gi ban tuong khong thich nhung nguoi kia thuyet phuc?',
  'Su that hai huoc nao ve nguoi kia chi ban moi biet?',
  'Neu tham gia gameshow tinh yeu, chung ta co thang khong?',
  'Cu chi nao cua nguoi kia lam ban phát dien (vi dang yeu)?',
  'Neu co phim ve chung ta, ai dong vai chinh?',

  // ── Hang ngay & Doi thuong (Daily Life) ───────────────────────
  'Dieu dau tien ban nghi den khi thuc day la gi?',
  'Ban thich nhat dieu gi ve buoi toi cung nhau?',
  'Mon an nao ban muon nau cho nguoi kia?',
  'Rutin buoi sang ly tuong cua chung ta?',
  'Ban muon di dau vao cuoi tuan nay?',
  'Dieu gi ban muon lam truoc khi ngu?',
  'Ban thich lam gi khi troi mua o nha cung nhau?',
  'Bu cua chung ta tot nhat la gi?',
  'Dieu gi ban muon thay doi trong lich trinh hang ngay?',
  'Khi met moi, ban muon nguoi kia lam gi?',

  // ── Tin tuong & Cam ket (Trust) ─────���─────────────────────────
  'Dieu gi khien ban tin tuong nguoi kia nhat?',
  'Ban hieu the nao la chung thuy?',
  'Dieu gi ban se khong bao gio giau nguoi kia?',
  'Ban cam thay the nao khi nguoi kia co ban khac gioi?',
  'Dieu gi ban muon hua voi nguoi kia?',
  'Ban nghi su trung thuc quan trong den muc nao?',
  'Khi nao ban cam thay can khong gian rieng?',
  'Ban muon duoc tu do den muc nao trong moi quan he?',
  'Dieu gi ban tin la nen chia se voi nhau?',
  'Ban se lam gi neu chung ta gap kho khan tai chinh?',

  // ── Bo sung (Extra) ───────────────────────────────────────────
  'Mot tu de mo ta moi quan he cua chung ta?',
  'Dieu ban biet on nhat ve nguoi kia?',
  'Neu chi co 3 tu de noi voi nguoi kia, ban noi gi?',
  'Dieu gi ban muon lam nhieu hon cho nguoi kia?',
  'Ban muon chung ta tao nen truyen thong gi rieng?',
  'Dieu gi ban thay la dac biet nhat ve moi quan he cua chung ta?',
  'Ban se giu ky vat gi ve chung ta mai mai?',
  'Loi nhan gui nguoi kia ngay hom nay?',
  'Dieu gi ban muon cam on nguoi kia?',
  'Ban muon viet gi trong nhat ky chung cua chung ta hom nay?',
];
